### ISSUE TITLE
Sem forks

### ISSUE THREAD

**Issue by drbeco** [camila-ito/grafodirigido01#1]
@renvicente , apague o fork que fez.

Todos devem trabalhar neste único repositório (usuário @camila-ito ), sem forks.

Label: **urgent** !

**Comment by renvicente** [comment]
Eu não fiz fork, professor.

**Comment by renvicente** [comment]
Tem razão, tinha feito mesmo. Não sei como, deve ter sido descuido.

**Comment by drbeco** [comment]
`<close>`
