### ISSUE TITLE
API

### ISSUE THREAD

**Issue by cajubavictor** [camila-ito/grafodirigido01#2]
olá galera, estava pesquisando funções de arco , e encontrei essa que achei interessante.
void arc(BITMAP *bmp, int x, y, fixed ang1, ang2, int r, int color);

contudo precisamos encontrar um ponto fixo, e o angulo de abertura.

**Comment by camila-ito** [comment]
O ponto fixo podia ser o centro da circunferência menor, uma das duas pelo menos.

**Comment by dnloliveira1** [comment]
void spline(BITMAP *bmp, const int points[8], int color);

no vetor iriamos fornecer pontos das circunferências e um terceiro ponto para fazer a curva. para achar esses pontos seria necessário achar a angulação fazer sin e cos... etc

**Comment by amandafilizola** [comment]
Acho q o uso do spline é mais simples não? Apenas é preciso os tres pontos. Não necessita de ângulo.

**Comment by amandafilizola** [comment]
Spline adicionado e usado no codigo.
