### ISSUE TITLE
Função Arc

### ISSUE THREAD

**Issue by cajubavictor** [camila-ito/grafodirigido01#3]
Galera, alguem tem alguma ideia de como fornecer os parâmetros para função arc ?

principalmente o centro e os ângulos??

**Comment by camila-ito** [comment]
Eu estava tentando achar uma relação entre o raio e um dos pontos centrais das circunferências menores, só que não entendi direito como funciona os ângulos dentro dessa função.

**Comment by gdbsm** [comment]
Eu pensei em colocar o centro do arco na mesma coordenada das circunferências, no eixo Y, para eles ficarem colineares e em uma posição, em relação ao eixo X, que o raio do arco tocasse as circunferências no ponto de tangência(por algum motivo acho que seria mais fácil de calcular assim). 

@camila-ito também to meio perdido nessa questão dos ângulos na função e não achei nada explicando no manual.

**Comment by camila-ito** [comment]
@gdbsm Mas se colocar no ponto de tangencia das funções não mudaria tanta coisa, a diferença seria que na distancia entre os centros teria que retirar o valor dos raios das circunferências menores. E isso não ajudaria em praticamente nada, só diminuiria a distancia a ser usada.

**Comment by amandafilizola** [comment]
Feito com spline. Código feito.
