### ISSUE TITLE
Spline

### ISSUE THREAD

**Issue by dnloliveira1** [camila-ito/grafodirigido01#4]
como já discutido na monitoria, vocês acham uma boa investir em estudo nessa função?

**Comment by camila-ito** [comment]
poderia ser usada já que a angulação para a função arc ainda é uma incógnita para mim

**Comment by dnloliveira1** [comment]
@cajubavictor por favor opine a respeito dessa maravilhosa função kkkkkk

**Comment by amandafilizola** [comment]
Acredito que o spline é a opção mais simples que a arc. Apoio.

**Comment by amandafilizola** [comment]
Spline adicionado e usado no codigo.
