### ISSUE TITLE
Considerações uteis para o próximo programa

### ISSUE THREAD

**Issue by dnloliveira1** [camila-ito/grafodirigido01#6]
- Circuito - trajeto fechado, ou seja, um caminho onde não há aresta repetida e os vértices inicial e final são idênticos / Circuito ~ Ciclo
- Todo caminho é um circuito

:facepunch: :facepunch: :stuck_out_tongue_winking_eye:

**Comment by rspds** [comment]
um circuito é, na verdade, um conjunto de caminhos

**Comment by cajubavictor** [comment]
Exatamente @rspds
